### ISSUE TITLE
bin url invalid

### ISSUE THREAD

**Issue by tzina97** [tzina97/netMHCpanW#11]
I tried both to remove the ending from the url (in two different ways) and also to remove the archive filename (from surrounding arguments as well) but it still doesn't accept the URL. :(

Is there a chance it has a problem with the URL itself? I remember you tested it though...

**Comment by tzina97** [comment]
@richelbilderbeek

**Comment by richelbilderbeek** [comment]
> Is there a chance it has a problem with the URL itself?

Nope, because -indeed- we tested that. You can verify yourself: just paste the URL in a browser URL bar. If a download starts, the URL is valid.

**Comment by tzina97** [comment]
I THINK I managed to fix the URL problem by changing the archive filename to actually match the ending of the url (because I tested different versions of the URL and none other worked) BUT because now the filename is is "/data.tar.gz" it gives me an error because in windows I think all paths are read with \  instead of /

install_netMHCpan_bin()
  Error in netMHCpan::check_can_create_file(filename = netMHCpan_bin_tarfile_path,  : 
    Cannot create a file at location C:\Users\tzina\AppData\Local/NetMHCpan-4.1/data.tar.gz
  Calls: install_netMHCpan_bin -> <Anonymous>
  Execution halted

**Comment by richelbilderbeek** [comment]
I think `normalizePath("C:\Users\tzina\AppData\Local/NetMHCpan-4.1/data.tar.gz")` will solve that problem :-)

**Comment by richelbilderbeek** [comment]
Also, AFAIK, `file.path("A", "B")` produces `A/B` on Linux and `A\B` on Windows :+1:
