### ISSUE TITLE
Build error due to file permissions

### ISSUE THREAD

**Issue by richelbilderbeek** [tzina97/netMHCpanW#4]
I just saw [here](https://github.com/tzina97/netMHCpanW/runs/2965395716?check_suite_focus=true#step:12:11) that the build now fails due to file permissions:

```
Run if [[ "$INSTALL_NETMHCPAN" == true ]]; then ./scripts/install_netMHCpan.sh; fi
/home/runner/work/_temp/858b4b38-452b-42bd-ae5c-2f775d6032c9.sh: line 1: ./scripts/install_netMHCpan.sh: Permission denied
```

I am unsure if a Windows user can fix this. Under Linux, it would be `chmod +x install_netMHCpan.sh` to **mod**ify the file permissions to add (`+`) the right to e**x**ecute.

**Comment by richelbilderbeek** [comment]
If you want, I can do so :-)

**Comment by tzina97** [comment]
I tried a few different ways but it doesn't seem to be working. :( Could you try it? Thank you!

**Comment by richelbilderbeek** [comment]
Hi @tzina97, just created a PR at https://github.com/tzina97/netMHCpanW/pull/5 :-)

**Comment by tzina97** [comment]
The new file showed the same issue. I tried to use chmod but it didn't seem to change anything. @richelbilderbeek Could you maybe fix it again please?

**Comment by richelbilderbeek** [comment]
Sure, here it is: https://github.com/tzina97/netMHCpanW/pull/13
