### ISSUE TITLE
Fix warning: Found the following hidden files and directories

### ISSUE THREAD

**Issue by richelbilderbeek** [tzina97/netMHCpanW#8]
There is a warning in the build, taken from [here](https://github.com/tzina97/netMHCpanW/runs/2998542272?check_suite_focus=true#step:13:36):

```
Found the following hidden files and directories:
  .github
```

Do so by adding `.github` to the `.Rbuildignore` file

**Comment by tzina97** [comment]
Fixed! Thank you
